// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:GloeilampSysteem.DataAccessLayer.DAL.padlock")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:GloeilampSysteem.DataAccessLayer.JsonDAL.lightswitches")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:GloeilampSysteem.DataAccessLayer.DapperDAL.lightSwitches")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.CreateLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)~GloeilampSysteem.BusinessLayer.Lightswitch")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.JsonDAL.CreateDummyData")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.CreateLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)~GloeilampSysteem.BusinessLayer.Lightswitch")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.DeleteLamp(GloeilampSysteem.BusinessLayer.Lamp)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.DeleteLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.ReadLightswitches~System.Collections.Generic.List{GloeilampSysteem.BusinessLayer.Lightswitch}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.UpdateLamp(GloeilampSysteem.BusinessLayer.Lamp)~GloeilampSysteem.BusinessLayer.Lamp")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.UpdateLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)~GloeilampSysteem.BusinessLayer.Lightswitch")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.ConnectLampsToLightswitches(GloeilampSysteem.BusinessLayer.Lightswitch)~System.Collections.Generic.List{GloeilampSysteem.BusinessLayer.Lamp}")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.CreateLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)~GloeilampSysteem.BusinessLayer.Lightswitch")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.DeleteLamp(GloeilampSysteem.BusinessLayer.Lamp)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.DeleteLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.ReadLamp(System.Int32)~GloeilampSysteem.BusinessLayer.Lamp")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.ReadLightswitch(System.Int32)~GloeilampSysteem.BusinessLayer.Lightswitch")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.ReadLightswitches~System.Collections.Generic.List{GloeilampSysteem.BusinessLayer.Lightswitch}")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.UpdateLamp(GloeilampSysteem.BusinessLayer.Lamp)~GloeilampSysteem.BusinessLayer.Lamp")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.DapperDAL.UpdateLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)~GloeilampSysteem.BusinessLayer.Lightswitch")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.CreateLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)~GloeilampSysteem.BusinessLayer.Lightswitch")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.DeleteLamp(GloeilampSysteem.BusinessLayer.Lamp)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.DeleteLightswitch(GloeilampSysteem.BusinessLayer.Lightswitch)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.ReadLightswitches~System.Collections.Generic.List{GloeilampSysteem.BusinessLayer.Lightswitch}")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.UpdateLamp(GloeilampSysteem.BusinessLayer.Lamp)~GloeilampSysteem.BusinessLayer.Lamp")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:GloeilampSysteem.DataAccessLayer.SQLDAL.ReadLightswitches~System.Collections.Generic.List{GloeilampSysteem.BusinessLayer.Lightswitch}")]
